local ns = {}

local function loadModule(path)
    local chunk = assert(loadfile(path))
    chunk("TwinkTracker", ns)
end

loadModule("Defaults.lua")
loadModule("Data/Brackets.lua")
loadModule("Data/Basics.lua")
loadModule("Data/Bis.lua")
loadModule("Data/Enchants.lua")
loadModule("Data/Consumables.lua")
loadModule("Data/Guides.lua")
loadModule("Data/ClassTiers.lua")
loadModule("Data/PvPEvents.lua")
loadModule("Data/Exploration.lua")
loadModule("Data/BracketRegistry.lua")
loadModule("Data/Bracket29/Bis.lua")
loadModule("Data/Bracket29/Enchants.lua")
loadModule("Data/Bracket29/Consumables.lua")
loadModule("Data/Bracket29/Basics.lua")
loadModule("Data/Bracket29/Guides.lua")
loadModule("Data/Bracket29/ClassTiers.lua")
loadModule("Data/Bracket29/Exploration.lua")
loadModule("Data/Bracket29/Register.lua")
loadModule("Database.lua")

local db = ns.Database:Initialize({
    frame = { point = "INVALID", x = 9001, y = -9001 },
    selectedClass = "INVALID",
    selectedTab = "INVALID",
    xpLockdown = "yes",
    showMinimapIcon = "yes",
    checklist = "invalid",
})

assert(db.frame.point == "CENTER")
assert(db.frame.x == 5000 and db.frame.y == -5000)
assert(db.frame.width == 1100 and db.frame.height == 700)
assert(db.selectedClass == "DRUID")
assert(db.selectedBracket == 19)
assert(db.selectedTab == "BIS")
assert(db.selectedPage == "GEAR")
assert(db.selectedGearSection == "GEAR")
assert(db.selectedGuide == "FIRST_AID")
assert(db.minimapAngle == 225)
assert(db.showMinimapIcon == true)
assert(db.selectedSlot == "HEAD")
assert(db.xpLockdown == false)
assert(type(db.checklist) == "table")

assert(ns.Database:SetSelectedClass("ROGUE"))
assert(ns.Database:Get().selectedClass == "ROGUE")
assert(not ns.Database:SetSelectedClass("DEMONHUNTER"))
assert(ns.Database:SetSelectedBracket(19))
assert(ns.Database:Get().selectedBracket == 19)
assert(ns.Database:SetSelectedBracket(29))
assert(ns.Database:Get().selectedBracket == 29)
assert(not ns.Database:SetSelectedBracket(39))
assert(ns.Database:Get().selectedBracket == 29)
local bracket29 = ns.Database:Initialize({ selectedBracket = 29 })
assert(bracket29.selectedBracket == 29)
assert(ns.Database:SetSelectedBracket(19))
assert(ns.Database:SetSelectedClass("ROGUE"))
assert(ns.Database:SetSelectedSlot("RANGED"))
assert(not ns.Database:SetSelectedSlot("RELIC"))
assert(ns.Database:SetSelectedTab("BIS"))
assert(not ns.Database:SetSelectedTab("UNKNOWN"))
assert(ns.Database:SetSelectedPage("BASICS"))
assert(ns.Database:Get().selectedPage == "BASICS")
assert(ns.Database:SetSelectedPage("CLASS_TIERS"))
assert(ns.Database:Get().selectedPage == "CLASS_TIERS")
assert(ns.Database:SetSelectedPage("PVP"))
assert(ns.Database:Get().selectedPage == "PVP")
assert(ns.Database:SetSelectedPage("COMMUNITY"))
assert(ns.Database:Get().selectedPage == "COMMUNITY")
assert(ns.Database:SetSelectedPage("EXPLORATION"))
assert(ns.Database:Get().selectedPage == "EXPLORATION")
assert(not ns.Database:SetSelectedPage("CHECKLIST"))
assert(ns.Database:SetSelectedPage("GUIDES"))
assert(ns.Database:SetSelectedGuide("FISHING"))
assert(ns.Database:Get().selectedGuide == "FISHING")
assert(not ns.Database:SetSelectedGuide("COOKING"))
assert(ns.Database:SetSelectedGearSection("ENCHANTS"))
assert(ns.Database:Get().selectedGearSection == "ENCHANTS")
assert(ns.Database:SetSelectedGearSection("CONSUMABLES"))
assert(not ns.Database:SetSelectedGearSection("UNKNOWN"))
assert(ns.Database:SetChecklistDone("gear_plan", true))
assert(ns.Database:IsChecklistDone("gear_plan"))
assert(ns.Database:SetChecklistDone("gear_plan", false))
assert(not ns.Database:IsChecklistDone("gear_plan"))

ns.Database:SetMinimapAngle(90)
assert(ns.Database:Get().minimapAngle == 90)
ns.Database:SetMinimapAngle(900)
assert(ns.Database:Get().minimapAngle == 360)
ns.Database:SetShowMinimapIcon(false)
assert(ns.Database:Get().showMinimapIcon == false)
ns.Database:SetShowMinimapIcon(true)
assert(ns.Database:Get().showMinimapIcon == true)

ns.Database:SetFramePosition("TOP", 10, 20)
assert(ns.Database:Get().frame.point == "TOP")
ns.Database:SetFrameSize(2000, 100)
assert(ns.Database:Get().frame.width == 1500)
assert(ns.Database:Get().frame.height == 620)
ns.Database:SetFrameSize(100, 700)
assert(ns.Database:Get().frame.width == 880)
ns.Database:ResetFramePosition()
assert(ns.Database:Get().frame.point == "CENTER")
assert(ns.Database:Get().frame.width == 1100)
assert(ns.Database:Get().frame.height == 700)

print("test_database.lua: ok")
